### ISSUE TITLE
Test: Analysis ended with XX errors

### ISSUE THREAD

**Issue by nick-youngblut** [derijkp/scywalker#4]
I've run the test dataset twice:

- First run: `Analysis ended with 82 errors`
- Second run: `Analysis ended with 94 errors`

Reprex:

```bash
wget https://github.com/derijkp/scywalker/releases/download/v0.108.0/scywalker_test.tar.gz \
  && tar xvzf scywalker_test.tar.gz \
  && cd scywalker_test

~/bin/scywalker-0.108.0-Linux-x86_64/scywalker_makerefdir -organelles '' g17 genome.fa genes.gtf

~/bin/scywalker-0.108.0-Linux-x86_64/scywalker -v 1 -d 8 \
	-refdir g17 \
	-sc_expectedcells 183 \
	-cellmarkerfile markers_chr17.tsv \
	-threads 6 \
	test10x
```

The list of `err` logs for the 2nd run:

```
distrreg-samples__mix1__gene_counts-isoquant_sc-sminimap2_splice-mix1.tsv.err
distrreg-samples__mix1__isoform_counts-isoquant_sc-sminimap2_splice-mix1.tsv.err
distrreg-samples__mix1__read_assignments-isoquant_sc-sminimap2_splice-mix1.tsv.zst.err
distrreg-samples__mix2__gene_counts-isoquant_sc-sminimap2_splice-mix2.tsv.err
distrreg-samples__mix2__isoform_counts-isoquant_sc-sminimap2_splice-mix2.tsv.err
distrreg-samples__mix2__read_assignments-isoquant_sc-sminimap2_splice-mix2.tsv.zst.err
iso_compar-gene_counts-isoquant_sc-test10x.err
iso_compar-gene_counts-test10x.err
iso_compar-isoform_counts-isoquant_sc-test10x.err
iso_compar-isoform_counts-test10x.err
iso_compar-totalcounts-isoquant_sc-test10x.err
iso_compar-totalcounts-test10x.err
isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.err
isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-55615535-62204609.err
isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-71399270-83257441.err
isoquant-isoquant_sc-sminimap2_splice-mix2-chr17-0-11039388.err
isoquant-isoquant_sc-sminimap2_splice-mix2-chr17-14573600-21969268.err
isoquant-isoquant_sc-sminimap2_splice-mix2-chr17-24840903-52275265.err
isoquant-isoquant_sc-sminimap2_splice-mix2-chr17-62204609-65342621.err
isoquant-isoquant_sc-sminimap2_splice-mix2-chr17-71399270-83257441.err
isoquant_join-isoquant_sc-sminimap2_splice-mix1.err
isoquant_join-isoquant_sc-sminimap2_splice-mix2.err
isoquant_sc_join_gene-isoquant_sc-sminimap2_splice-mix1.err
isoquant_sc_join_gene-isoquant_sc-sminimap2_splice-mix2.err
isoquant_sc_join_iso-isoquant_sc-sminimap2_splice-mix1.err
isoquant_sc_join_iso-isoquant_sc-sminimap2_splice-mix2.err
isquant_convert-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.err
isquant_convert-isoquant_sc-sminimap2_splice-mix1-chr17-55615535-62204609.err
isquant_convert-isoquant_sc-sminimap2_splice-mix1-chr17-71399270-83257441.err
isquant_convert-isoquant_sc-sminimap2_splice-mix2-chr17-0-11039388.err
isquant_convert-isoquant_sc-sminimap2_splice-mix2-chr17-14573600-21969268.err
isquant_convert-isoquant_sc-sminimap2_splice-mix2-chr17-24840903-52275265.err
isquant_convert-isoquant_sc-sminimap2_splice-mix2-chr17-62204609-65342621.err
isquant_convert-isoquant_sc-sminimap2_splice-mix2-chr17-71399270-83257441.err
isquant_sc_count-chr17-0-11039388-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-0-11039388-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-11039388-14573600-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-11039388-14573600-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-14573600-21969268-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-14573600-21969268-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-21969268-24840903-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-21969268-24840903-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-24840903-52275265-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-24840903-52275265-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-52275265-55615535-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-52275265-55615535-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-55615535-62204609-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-55615535-62204609-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-62204609-65342621-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-62204609-65342621-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-65342621-70573759-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-65342621-70573759-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-70573759-71399270-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-70573759-71399270-isoquant_sc-sminimap2_splice-mix2.err
isquant_sc_count-chr17-71399270-83257441-isoquant_sc-sminimap2_splice-mix1.err
isquant_sc_count-chr17-71399270-83257441-isoquant_sc-sminimap2_splice-mix2.err
pb_compar-gene_counts-scsorter-test10x.err
pb_compar-gene_counts-sctype-test10x.err
pb_compar-gene_counts-test10x.err
pb_compar-pb_gene_counts_colinfo-scsorter-test10x.err
pb_compar-pb_gene_counts_colinfo-sctype-test10x.err
pb_compar-pb_gene_counts_colinfo-test10x.err
pb_compar-pb_isoform_counts_colinfo-scsorter-test10x.err
pb_compar-pb_isoform_counts_colinfo-sctype-test10x.err
pb_compar-pb_isoform_counts_colinfo-test10x.err
pb_compar-pb_isoform_counts-scsorter-test10x.err
pb_compar-pb_isoform_counts-sctype-test10x.err
pb_compar-pb_isoform_counts-test10x.err
reportscombine_stats-test10x.err
sc_celltyper_scsorter-isoquant_sc-sminimap2_splice-mix1.err
sc_celltyper_scsorter-isoquant_sc-sminimap2_splice-mix2.err
sc_celltyper_scsorter_scgenefile10x-scsorter-isoquant_sc-sminimap2_splice-mix1.err
sc_celltyper_scsorter_scgenefile10x-scsorter-isoquant_sc-sminimap2_splice-mix2.err
sc_celltyper_sctype-isoquant_sc-sminimap2_splice-mix1.err
sc_celltyper_sctype-isoquant_sc-sminimap2_splice-mix2.err
sc_counts_filtered-isoquant_sc-sminimap2_splice-mix1.err
sc_counts_filtered-isoquant_sc-sminimap2_splice-mix2.err
sc_filter_default_r-isoquant_sc-sminimap2_splice-mix1.err
sc_filter_default_r-isoquant_sc-sminimap2_splice-mix2.err
sc_filter_default_scgenefile10x-isoquant_sc-sminimap2_splice-mix1.err
sc_filter_default_scgenefile10x-isoquant_sc-sminimap2_splice-mix2.err
sc_filter_default_scisoformfile10x-isoquant_sc-sminimap2_splice-mix1.err
sc_filter_default_scisoformfile10x-isoquant_sc-sminimap2_splice-mix2.err
sc_filter_write_cellinfo-isoquant_sc-sminimap2_splice-mix1.err
sc_filter_write_cellinfo-isoquant_sc-sminimap2_splice-mix2.err
sc_pseudobulk-scsorter-isoquant_sc-sminimap2_splice-mix1.err
sc_pseudobulk-scsorter-isoquant_sc-sminimap2_splice-mix2.err
sc_pseudobulk-sctype-isoquant_sc-sminimap2_splice-mix1.err
sc_pseudobulk-sctype-isoquant_sc-sminimap2_splice-mix2.err
scywalker_report_mix1.err
scywalker_report_mix2.err
```

An example error log:

```
$ cat test10x/log_jobs/err/pb_compar-gene_counts-scsorter-test10x.err
dependency /home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/samples/mix1/pb_gene_counts-scsorter-isoquant_sc-sminimap2_splice-mix1.tsv.zst not found
    while executing
"error "dependency /home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/samples/mix1/pb_gene_counts-scsorter-isoquant..."
    invoked from within
"if {![job_file_or_link_exists /home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/samples/mix1/pb_gene_counts-scsor..."
    (file "/home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/log_jobs/run/pb_compar-gene_counts-scsorter-test10x.run" line 17)
    invoked from within
"source /home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/log_jobs/run/pb_compar-gene_counts-scsorter-test10x.run"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $file]"
    (procedure "cg_source" line 4)
    invoked from within
"cg_$action {*}$args"
    invoked from within
cg source /home/nickyoungblut/bin/scywalker-0.108.0-Linux-x86_64/test_run/scywalker_test/test10x/log_jobs/run/pb_compar-gene_counts-scsorter-test10x.run
```

My system info:

* Ubuntu 22.04.3
* 128 threads
* ~800 Gb memory

**Comment by wdecoster** [comment]
Thank you for reporting this. @derijkp is off for a few days, but will get back to you upon his return.

Best regards,
Wouter

**Comment by derijkp** [comment]
Hi,

Thank you for your error report.
Given the number of errors, likely something something went wrong in an early job (e.g. making the bam file), causing subsequent jobs dependent on the results to fail as well. The included example err file is from such a subsequent job (missing a file it needs that should have been made by an earlier job)
To identify the original error,  can you have a look at (or send) the (overview) logfile, which should be named process_project_test10x.*.error. This is a tab-separated list of jobs (in order of dependencies) with status, messages, etc; we are looking for the first job with error status in this list.

I will add a section on troubleshooting to the docs (and in messages) to make this easier/clearer.

Peter

**Comment by nick-youngblut** [comment]
Here's the error log: [process_project_test10x.2024-03-14_15-41-11-239.error.zip](https://github.com/derijkp/scywalker/files/14669132/process_project_test10x.2024-03-14_15-41-11-239.error.zip)

It appears that the errors start at the `isoquant-isoquant_sc-sminimap2_splice` jobs.

**Comment by derijkp** [comment]
The error message for this one is unfortunately not very informative (child process exited abnormally)

Can you also provide the run file:
log_jobs/run/isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.run
and the bam file
so I can check what might be wrong with them.

Can you also try running that run file directly to check if the error is reproducible on your machine:
./log_jobs/run/isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.run

**Comment by nick-youngblut** [comment]
Here the "*.run" file (why not the standard "*.sh" file extension?): [isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.run.zip](https://github.com/derijkp/scywalker/files/14746880/isoquant-isoquant_sc-sminimap2_splice-mix1-chr17-24840903-52275265.run.zip)

I'm running the job now; I'll let you know if it finishes successfully.

I'm assuming that such tests do not occur on your machine. It might be best to reproduce my machine via docker. Something like:

```dockerfile
FROM ubuntu:20.04

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
      wget \
      build-essential \
      wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/derijkp/scywalker/releases/download/v0.108.0/scywalker_test.tar.gz \
  && tar xvzf scywalker_test.tar.gz \
  && rm -f scywalker_test.tar.gz

CMD ["scywalker", "-h"]
```

Moreover, such software testing errors could be identified via GitHub Actions. An example actions yaml file:

```yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: scywalker

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: "ubuntu-20.04"}
          - {os: "ubuntu-22.04"}
         
    steps:
      - id: "Checkout"
        name: "Checkout code"
        uses: actions/checkout@v3
      - id: "Install"
        name: "scywalker install"
        run: |
          wget https://github.com/derijkp/scywalker/releases/download/v0.108.0/scywalker_test.tar.gz
          tar xvzf scywalker_test.tar.gz
          rm -f scywalker_test.tar.gz
       - id: "Test download"
          name: "Download scywalker test data"
          run: |
            wget https://github.com/derijkp/scywalker/releases/download/v0.108.0/scywalker_test.tar.gz
            tar xvzf scywalker_test.tar.gz
       - id: "Test create ref"
         name: "Create scywalker ref"
         run: |
             cd scywalker_test
             ../scywalker-0.108.0-Linux-x86_64/scywalker_makerefdir -organelles '' g17 genome.fa genes.gtf
       - id: "Test run"
         name: "Run scywalker on test"
         run: |
           cd scywalker_test
           ../scywalker-0.108.0-Linux-x86_64/scywalker -v 1 -d 8  -refdir g17 -sc_expectedcells 183 -cellmarkerfile markers_chr17.tsv -threads 2 test10x
```

Using the docker image and/or Github actions can save a lot of time with debugging issues.
